apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: revoredo/api-produto:latest
        resources:
          requests:
            memory: 32Mi
            cpu: 150m
          limits:
            memory: 64Mi
            cpu: 300m
        ports:
        - containerPort: 80
          name: http
        env:
        - name: Mongo__User
          value: mongodbuser 
        - name: Mongo__Password
          value: mongodbpwd 
        - name: Mongo__Host
          value: mongo-service
        - name: Mongo__DataBase
          value: admin
      