apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: revoredo/api-produto:10
        resources:
          requests:
            memory: 32Mi
            cpu: 150m
          limits:
            memory: 64Mi
            cpu: 300m
        ports:
        - containerPort: 80
          name: http
        env:
        - name: Mongo__User
          value: mongodbuser 
        - name: Mongo__Password
          value: mongodbpwd 
        - name: Mongo__Host
          value: mongo-service
        - name: Mongo__DataBase
          value: admin
      