apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9216"
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.8
        resources: 
          requests:
            memory: "256Mi"
            cpu: "1000m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongodbuser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongodbpwd
      - name: mongodbexporter
        image: fabricioveronez/mongo_exporter
        resources: {}
        ports:
          - containerPort: 9216
        env:
          - name: MONGODB_URI
            value: mongodb://mongodbuser:mongodbpwd@localhost:27017

  